name: Build and Test Flask API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies and run app
      run: |
        pip install flask
        python app.py &
        sleep 3
        curl -X POST http://127.0.0.1:5000/calculate \
             -H "Content-Type: application/json" \
             -d '{"num1":10,"num2":24,"operation":"multiply"}'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t flask-calculator-api .
